/** Lucky Numbers (2017-8-28)
 *
 * Natural numbers in a set generated by a sieve.
 * Eliminates numbers based on their position in the remaining set.
 *
 * Ex:
 * Starting with: 1 2 3 4 5 6 7 8 9 10 11 12
 *
 * -- Remove every even number:
 *  1 3 5 7 9...
 *  After 1, the next number is 3: Remove every 3rd element:
 *  1 3 7 9 13...
 *  Next number is 7: Remove every 7th element:
 *  1 3 7 9 13 15 21...
*/


